### ISSUE TITLE
I put erlang-rebar in .emacs/private dir, But 'Cannot open load file'

### ISSUE THREAD

**Issue by wudixiaotie** [sirn/dotfiles#1]
`dotspacemacs-configuration-layer-path '("~/.emacs.d/private")`

But still give me 'File mode specification error: (file-error "Cannot open load file" "no such file or directory" "erlang-rebar")',

Can you help me?

**Comment by wudixiaotie** [comment]
My bad, I put erlang-rebar.el in` ~/.emacs.d/private/erlang-rebar/` it should in ` ~/.emacs.d/private/erlang-rebar/local/erlang-rebar`.
After I put it in there, there is no mistake. But still can not find .hrl file in my project, why?

**Comment by sirn** [comment]
The `erlang-rebar.el` only add the path to `ebin/` of rebar dependencies (by running `rebar3 path`) into `inferior-erlang-machine-options` variable. It's equivalent of running `erl -pa $(rebar3 path)`, could you confirm if the command could find the dependency you're looking for?

**Comment by wudixiaotie** [comment]
If I run `erl -pa $(rebar3 path)`, it can find all I need. But in spacemacs, It still could not find .hrl files. What could I do?

**Comment by wudixiaotie** [comment]
I found out, I did some change, and I works. I will pull a request to you.

**Comment by sirn** [comment]
Glad to see you managed to get it to work.

At one point I think I should repack this and submit to ELPA (& Spacemacs). Thanks for the PR!
